### ISSUE TITLE
Text format for translations

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#5]
For user, translations are expected to be in text format:

- Can be edited manually
- Can be exported/imported to web translation services
- Easy to track diffs

C sources will be generated by compiler utility, and to expected to be edited.

Default file type is YAML. Alternative - JSON (will be supported automatically as YAML subset).

## Format

**TBD**

**Comment by puzrin** [comment]
Format. Something like this:

```yaml
'en-GB':
  Nut: [ Nut, Nuts ]

'ru-RU':
  Settings: Настройки
  Nut: [ Гайка, Гайки, Гаек ]
  'LVGL is awesome!': ~ # null, added by extractor as mark to translate
```

Notes:
  - for default locate plurals are enougth
  - plural names (`one`, `two`, `many`, ...) are not used, because sequence is strict for each language, and optional (skippable) forms are at the end.

**Comment by kisvegabor** [comment]
Looks good to me. `en_GB` and `ru_RU` should be compiled to C file and array names as  I suggested [here](https://github.com/littlevgl/i18n/issues/2#issuecomment-462016743) (I used different naming but doesn't really matter)

**Comment by puzrin** [comment]
http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/index.html - hear is nice list of available translations formats

My suggestion is close to Ruby, by they supports plurals in different way: https://github.com/translate/translate/issues/3615

Still not sure what is better:

- Arrays are comfortable for manual edits, when no translators used.
- Named plurals are better for web translators, because standard format should be supported for import/export

Probably we just need to support both and add format option to scripts. Need to dig web translator docs to decide.

**Comment by puzrin** [comment]
For info: at web projects plurals are ~ 15% of phrases.

Ruby's way:

```yaml
'en-GB':
  Nut:
    one: Nut
    many: Nuts

'ru-RU':
  Settings: Настройки
  Nut:
    one: Гайка
    few: Гайки
    many: Гаек
  'LVGL is awesome!': ~ # null, added by extractor as mark to translate
```

May be, not so bad...
